### ISSUE TITLE
CLA is not linked on website

### ISSUE THREAD

**Issue by QuLogic** [dreamworksanimation/openmoonray#11]
The [License page](https://docs.openmoonray.org/license/) says that there is a CLA, but does not link to anything.

[The `CONTRIBUTING.md`](https://github.com/dreamworksanimation/openmoonray/blob/9b629e0999bfe2394ad56d31c3314c5199c4db3c/CONTRIBUTING.md#contributor-license-agreements) does contain the link.

**Comment by randypacker** [comment]
Thanks QuLogic, we've updated the license page to link to CONTRIBUTING.
