### ISSUE TITLE
Failed to find plugin

### ISSUE THREAD

**Issue by szuhow** [dreamworksanimation/openmoonray#152]
I am having issue with using hydra commands, like hd_usd2rdl/hd_render, as there is Coding error as below:

Coding Error: in _GetPluginForType at line 146 of /build/USD-prefix/src/USD/pxr/usd/ar/resolver_v2.cpp -- Failed to find plugin for ArDefaultResolver
Segmentation fault

My setup is: I have build moonray app on Centos 7 in docker container, then I have save the docker image and then pulled shared libraries from docker container to my Centos 7 host. Other commands (like moonray or arras_render) are working, but hydra is working only in container, but not on host. How to resolve that issue?

Best regards,
R

**Comment by jlanz** [comment]
I suspect that the RPATH/RUNPATH in the USD libs that you moved from the container to your host could be causing the issue, but I am not sure.
