### ISSUE TITLE
Docker building error

### ISSUE THREAD

**Issue by sotoxicstar** [dreamworksanimation/openmoonray#22]
Hello, I got this message when I tried to build the MoonRay in a Docker container and I don't know how to fix it
![3M-LQ3sXVmQ](https://user-images.githubusercontent.com/79450785/225764921-92714070-2c2a-43fe-a4cf-63598eac7074.jpg)

**Comment by jlanz** [comment]
It looks like you may have forgotten to add the `--recurse-submodules` flag when you cloned the repo.
https://docs.openmoonray.org/getting-started/installation/cloning-the-repo/

You can probably run the following at the top of the source tree  to populate the submodules:
`git submodule update --init --recursive --checkout`
