### ISSUE TITLE
error: invalid conversion from 'int' to 'OptixDenoiserAlphaMode'

### ISSUE THREAD

**Issue by ryanrussell** [dreamworksanimation/openmoonray#24]
Following the [docker build steps](https://docs.openmoonray.org/getting-started/installation/building-moonray/building-moonray-container/), I am seeing a failure on step 3.

After building `openmoonray_build`, the following step fails:

`cmake --build --preset container-release -- -j 64`

```bash
/openmoonray/moonray/mcrt_denoise/lib/denoiser/OptixDenoiserImpl.cc: In constructor 'moonray::denoiser::OptixDenoiserImpl::OptixDenoiserImpl(int, int, bool, bool, std::string*)':
/openmoonray/moonray/mcrt_denoise/lib/denoiser/OptixDenoiserImpl.cc:110:36: error: invalid conversion from 'int' to 'OptixDenoiserAlphaMode' [-fpermissive]
  110 |     mDenoiserParams.denoiseAlpha = 0;     // don't denoise alpha
      |                                    ^
      |                                    |
      |                                    int
gmake[2]: *** [moonray/mcrt_denoise/lib/denoiser/CMakeFiles/denoiser.dir/build.make:104: moonray/mcrt_denoise/lib/denoiser/CMakeFiles/denoiser.dir/OptixDenoiserImpl.cc.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:10268: moonray/mcrt_denoise/lib/denoiser/CMakeFiles/denoiser.dir/all] Error 2
gmake[1]: *** Waiting for unfinished jobs....
```

Any suggestions would be greatly appreciated.

**Comment by kjeffery** [comment]
Hi @ryanrussell !

Are you using Optix 7.3? That appears to be a newer enum; we are tied to 7.3.

**Comment by ryanrussell** [comment]
Hey @kjeffery -- yes, I just grabbed the "latest" -- 7.5. You even have a big div saying to pin to 7.3, but I still goofed.

Thanks for the quick response! Hope this helps someone else who does the same
