### ISSUE TITLE
Isssue with building MoonRay

### ISSUE THREAD

**Issue by GucciPants** [dreamworksanimation/openmoonray#33]
Hello, 

I'm trying to build MoonRay and I am using CentOS-7,

I am at step 4, trying to use the "cmake --build --preset container-release -- -j 64" command. However, I get the following error:

**gmake: *** [Makefile:146: all] Error 2**

Here is the full screenshot: 
![WIUB1JW](https://user-images.githubusercontent.com/89215345/225990307-c8fa2c39-7e83-4643-8bb0-46132a31bc48.png)

**Comment by kjeffery** [comment]
Hi @GucciPants !

You're using a newer version of Optix than we support. Please limit your Optix version to 7.3.

**Comment by GucciPants** [comment]
Hey @kjeffery, The build was successful, thank you for the solution!
