### ISSUE TITLE
CLA for Non-Code Contributions?

### ISSUE THREAD

**Issue by AudreyBeard** [dreamworksanimation/openmoonray#46]
Does a would-be contributor need to sign a [C]CLA if their contributions contain no code or require otherwise specialized knowledge?

I ask because I was this 🤏 close to opening a PR on a fork of this repo for small README fixes (for duplicated and dead links), when I saw the contributing guidelines, which indicate I need a CCLA. I'm happy to look into that on my side, but wanna make sure it's necessary first.

**Comment by randypacker** [comment]
Great question AudreyBeard!  No, we'd prefer documentation fixes to be posted to a discussion thread, rather than pull requests.  We'll get a thread started soon for people to report these things.
