### ISSUE TITLE
Problem cloning the repository on windows

### ISSUE THREAD

**Issue by senjinthedragon** [dreamworksanimation/openmoonray#8]
Not sure if this might be caused because I'm trying to clone to a windows machine and not linux. But I'm getting the following error:

error: invalid path 'houdini/otls/Vop::DW_MOONRAY::AttributeMap::1.hda'
fatal: Unable to checkout 'ce861215cf2c4fec77c8decdabd96755917ae742' in submodule path 'moonray/moonray_dcc_plugins'

**Comment by lxhom** [comment]
I'm assuming you use Git Bash, and that does not have support for unsupported characters. You can use [MSys2](https://www.msys2.org/) & its Git binaries (`pacman -S git`) for this:

![WindowsTerminal_fuQR3BwThB](https://user-images.githubusercontent.com/73352734/225457795-d7b62b18-d4d8-4532-a865-31f10290d9a8.png)

**Comment by senjinthedragon** [comment]
Worse, I was doing it in a command prompt. I will switch to a suitable environment. Thanks.

**Comment by earlywill** [comment]
Just to add extra info, case it helps somebody.

Had same thing with git under powershell. Using WSL instead to run git things went through smoothly.

Was able to follow along with the rest of the Docker instructions afterwards.
