### ISSUE TITLE
OpenImageIOMoonray

### ISSUE THREAD

**Issue by adro79** [dreamworksanimation/openmoonray#9]
Hi there,

First of all, thanks for opening this awesome piece of software!
I'm trying to build OpenMoonRay on Arch Linux, but cmake fails to find OpenImageIO (which is installed).
It requieres to have a file called filesystem.h, which is part of a [custom build of oiio.](https://github.com/dreamworksanimation/cmake_modules/blob/3ebea9665cadadf67a76387f21c0548dd82d1bac/cmake/FindOpenImageIOMoonray.cmake)

Would be cool to know what is changed or be able to use the default filesystem.h

**Comment by alerque** [comment]
Same problem here. Also @adro79 I'm working on Arch packaging for this, please drop any solutions you have to *this* problem here of course, but if you get anything Arch specific I'd love to hear about it on the AUR package or my packaging repo.

**Comment by alerque** [comment]
Arch's *openimageio* package does have the file:

``` console
$ pacman -Ql openimageio | rg 'filesystem\.h'
openimageio /usr/include/OpenImageIO/filesystem.h
```

How have you setup your paths?

**Comment by adro79** [comment]
This is a comment from [FindOpenImageIOMoonray](https://github.com/dreamworksanimation/cmake_modules/blob/3ebea9665cadadf67a76387f21c0548dd82d1bac/cmake/FindOpenImageIOMoonray.cmake):

```
 # Find OpenImageIOMoonray, our modified version of openimageio
 # filesystem_impl.h is present only in this version
```

I don't know how different this file is from the normal **filesystem.h** but I don't think anyone can pass this error without this.

_PD: @alerque I saw your comment in my USD package from AUR, feel free to contact me if you want to co-maintain the package. After all I'm only a 3D Modeler with a enough technical knowledge to read some code. We can work together :)_

**Comment by alerque** [comment]
Thank, and sure I'd be happy to collaborate, I'm more of a coder than a 3D guy and don't know what half these spinning bits are even about ;-)

I see the *comments* about `filesystem_impl.h` but I don't see anything in in the code related to it yet. Also I *think* my build got past this point, but since I'm stuck on PXR stuff right now it's hard to tell. The OpenImageIO error I was stuck on at one point is past, but their might be more down the road that I haven't gotten to yet.

**Comment by rgwilson68** [comment]
Hi,
FindOpenImageIOMoonray is an old CMake module that should not be in use anymore : we just didn't get round to deleting it. It should never be invoked from the current build. I don't think that is what is causing cmake to fail finding OpenImageIO.

Usually OpenImageIO provides a CMake config file OpenImageIOConfig.cmake that cmake can find. With the build setup described on the MoonRay docs website, this goes into /installs/lib64/cmake/OpenImageIO. If OpenImageIO is pre-installed it might be in /usr/lib64/cmake or maybe /usr/local/lib64/cmake. You need to configure the CMAKE_PREFIX_PATH to somewhere above it : e.g. in the case of our build CMAKE_PREFIX_PATH is set to "/installs", and that is enough for cmake to find the config file.
